name: Test

on:
  push:
    branches: [github-actions, master]

jobs:
  firebase_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
